name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    #  - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    #  - name: Set up Docker Buildx
    #    uses: docker/setup-buildx-action@v3
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.IMAGE_TAG }}
          file: Dockerfile
  #      with:
  #       context: .
  #        platforms: linux/amd64,linux/arm64
  #        push: true
  #        file: Dockerfile
  #        tags: |
  #         balajicts/infra-devops:latest
  #         balajicts/infra-devops:1.0.0
  #         ${{ secrets.IMAGE_TAG }}
  #         ghcr.io/user/app:latest
  #         ghcr.io/user/app:1.0.0
